version: "3"

tasks:
  git:init:
    desc: Initialize Git repository
    cmds:
      - git init
      - git branch -M main

  git:commit:
    desc: Stage and commit changes
    cmds:
      - git add .
      - git commit -m "{{.MESSAGE}}"
    vars:
      MESSAGE: '{{default "chore: update project" .MESSAGE}}'

  git:push:
    desc: Push current branch to origin
    cmds:
      - git push -u origin main

  git:publish:
    desc: Commit and push changes
    cmds:
      - task: git:commit
        vars:
          MESSAGE: "{{.MESSAGE}}"
      - task: git:push
    vars:
      MESSAGE: '{{default "chore: update project" .MESSAGE}}'
