// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          pgtype.UUID
	CustomerID  pgtype.UUID
	Status      string
	TotalAmount pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type OrderItem struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	ProductID pgtype.UUID
	Quantity  int32
	UnitPrice pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
